name: Demo workflow
on:
  push:
    branches: main

jobs:
  print:
    runs-on: ubuntu-20.04
    steps:
      - name: Its an example for students
        run: echo Hi, Guys!
      - uses: actions/checkout@v3
